{% set name = "py-rattler" %}
{% set python_name = "py_rattler" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ python_name }}-{{ version }}.tar.gz
  sha256: 44c054a3fce6822240ad553ee8d94b97267edba1b717222ba8cd490085725baf

build:
  number: 0
  skip: true  # [py<38]

outputs:
  - name: py_rattler
    script: build_base.sh  # [unix]
    script: build_base.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - maturin >=1.2.2,<2                     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - python
        - maturin >=1.2.2,<2
        - pip
        - openssl       # [unix]
      run:
        - python
    test:
      imports:
        - rattler
      commands:
        - pip check
      requires:
        - pip

  - name: py-rattler
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('py_rattler', max_pin="x.x.x") }}
    test:
      imports:
        - rattler


about:
  home: https://github.com/mamba-org/rattler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A blazing fast library to work with the conda ecosystem

  # The remaining entries in this section are optional, but recommended.
  description: |
    Rattler is a library that provides common functionality used within the conda 
    ecosystem. The goal of the library is to enable programs and other libraries to 
    easily interact with the conda ecosystem without being dependent on Python. Its 
    primary use case is as a library that you can use to provide conda related 
    workflows in your own tools.
  dev_url: https://github.com/mamba-org/rattler

extra:
  recipe-maintainers:
    - baszalmstra
